// Monuments
export const FETCH_MONUMENTS_REQUEST = 'FETCH_MONUMENTS_REQUEST';
export const FETCH_MONUMENTS_SUCCESS = "FETCH_MONUMENTS_SUCCESS";
export const FETCH_MONUMENTS_FAILURE = "FETCH_MONUMENTS_FAILURE";
export const CHANGE_CANCEL_REQUEST = "CHANGE_CENCEL_REQUEST";
// Selected monument
export const CHANGE_SELECTED_MONUMENT = "CHANGE_SELECTED_MONUMENT";
export const CLOSE_SELECTED_MONUMENT_DIALOG = "CLOSE_SELECTED_MONUMENT_DIALOG";
// Transition
export const TRANSITION_START = "TRANSITION_START";
export const TRANSITION_END = "TRANSITION_END";
