// Monuments
export const FETCH_MONUMENTS_REQUEST = 'FETCH_MONUMENTS_REQUEST';
export const FETCH_MONUMENTS_SUCCESS = "FETCH_MONUMENTS_SUCCESS";
export const FETCH_MONUMENTS_FAILURE = "FETCH_MONUMENTS_FAILURE";
export const CHANGE_CANCEL_REQUEST = "CHANGE_CENCEL_REQUEST";
// Selected monument
export const CHANGE_SELECTED_MONUMENT = "CHANGE_SELECTED_MONUMENT";
