// Monuments
export const FETCH_MONUMENTS_REQUEST = 'FETCH_MONUMENTS_REQUEST';
export const FETCH_MONUMENTS_SUCCESS = "FETCH_MONUMENTS_SUCCESS";
export const FETCH_MONUMENTS_FAILURE = "FETCH_MONUMENTS_FAILURE";
export const CHANGE_CANCEL_REQUEST = "CHANGE_CENCEL_REQUEST";
// Selected monument
export const CHANGE_SELECTED_MONUMENT = "CHANGE_SELECTED_MONUMENT";
export const CLOSE_SELECTED_MONUMENT_DIALOG = "CLOSE_SELECTED_MONUMENT_DIALOG";
// Transition
export const TRANSITION_START = "TRANSITION_START";
export const TRANSITION_END = "TRANSITION_END";
// Filter
export const CHANGE_STATUSES = "CHANGE_STATUSES";
export const CHANGE_CONDITIONS = "CHANGE_CONDITIONS";
// Statuses
export const FETCH_STATUSES_REQUEST = 'FETCH_STATUSES_REQUEST';
export const FETCH_STATUSES_SUCCESS = "FETCH_STATUSES_SUCCESS";
export const FETCH_STATUSES_FAILURE = "FETCH_STATUSES_FAILURE";
export const CHANGE_STATUSES_CANCEL_REQUEST = "CHANGE_STATUSES_CENCEL_REQUEST";
// Conditions
export const FETCH_CONDITIONS_REQUEST = 'FETCH_CONDITIONS_REQUEST';
export const FETCH_CONDITIONS_SUCCESS = "FETCH_CONDITIONS_SUCCESS";
export const FETCH_CONDITIONS_FAILURE = "FETCH_CONDITIONS_FAILURE";
export const CHANGE_CONDITIONS_CANCEL_REQUEST = "CHANGE_CONDITIONS_CENCEL_REQUEST";